### ISSUE TITLE
Deprecated jQuery methods

### ISSUE THREAD

**Issue by janbiasi** [ellekasai/purplecoat.js#18]
You're using the method <code>.size()</code> which is [deprecated](http://api.jquery.com/size/) since jQuery 1.8.x. Please replace it with the <code>length</code> attribute, which jQuery also recommends on their site. Thanks!

**Comment by ellekasai** [comment]
Thank you so much! I replaced it :)
https://github.com/ellekasai/purplecoat.js/compare/1cea118ca633988043dcf3c7f23bfbd3c57f30e0...gh-pages

**Comment by janbiasi** [comment]
Thanks & you're welcome :)
